# Generated by Django 5.1.1 on 2024-09-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='chinese',
        ),
        migrations.RemoveField(
            model_name='note',
            name='english',
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
